export const HANDLE_NUMBER_BUTTON_CLICK = 'HANDLE_NUMBER_BUTTON_CLICK'
export const HANDLE_OPERATOR_BUTTON_CLICK = 'HANDLE_OPERATOR_BUTTON_CLICK'
export const GET_RESULT = 'GET_RESULT'
export const GET_DEFAULT_STATE = 'GET_DEFAULT_STATE'